import {MigrationInterface, QueryRunner} from "typeorm";

export class gameserverConfig1605533663691 implements MigrationInterface {
    name = 'gameserverConfig1605533663691'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("CREATE TABLE `match_config` (`id` int NOT NULL AUTO_INCREMENT, `configName` varchar(255) NOT NULL, `configHash` varchar(255) NOT NULL, `matchEndLength` smallint UNSIGNED NOT NULL, `warmUpLength` smallint UNSIGNED NOT NULL, `friendlyFireScale` float UNSIGNED NOT NULL, `mapLength` smallint UNSIGNED NOT NULL, `roundLength` smallint UNSIGNED NOT NULL, `preRoundLength` smallint UNSIGNED NOT NULL, `roundEndLength` smallint UNSIGNED NOT NULL, `roundLimit` smallint UNSIGNED NOT NULL, `allowGhostcam` tinyint NOT NULL, `playerVoteThreshold` float UNSIGNED NOT NULL, `autoBalanceTeams` tinyint NOT NULL, `playerVoteTeamOnly` tinyint NOT NULL, `maxTeamDamage` float UNSIGNED NOT NULL, `enablePlayerVote` tinyint NOT NULL, `autoSwapTeams` tinyint NOT NULL, `midGameBreakLength` smallint UNSIGNED NOT NULL, `nadeRestriction` tinyint NOT NULL, `globalVoicechat` tinyint NOT NULL, `muteDeadToTeam` tinyint NOT NULL, `ranked` tinyint NOT NULL, `private` tinyint NOT NULL, `gameModeId` int UNSIGNED NOT NULL, INDEX `idx_ranked` (`ranked`), UNIQUE INDEX `IDX_fbbc00f440d3e086650663cfbc` (`configName`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `gameserver_config` (`currentName` varchar(255) NOT NULL, `voteLength` smallint UNSIGNED NOT NULL, `gamePassword` varchar(255) NOT NULL, `reservedSlots` smallint UNSIGNED NOT NULL, `balanceClans` tinyint NOT NULL, `allowSkipMapVote` tinyint NOT NULL, `tempKickBanTime` smallint UNSIGNED NOT NULL, `autoRecordReplay` tinyint NOT NULL, `playerGameControl` tinyint NOT NULL, `enableMapVote` tinyint NOT NULL, `serverAdmins` varchar(255) NOT NULL DEFAULT '', `serverDescription` varchar(255) NOT NULL DEFAULT '', `website` varchar(255) NOT NULL DEFAULT '', `contact` varchar(255) NOT NULL DEFAULT '', `mapNoReplay` smallint UNSIGNED NOT NULL, `enableVoicechat` tinyint NOT NULL, `gameserverId` varchar(255) NOT NULL, `currentMatchConfigId` int NOT NULL, UNIQUE INDEX `REL_e81629bd2734cc6621e92a8897` (`gameserverId`), PRIMARY KEY (`gameserverId`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `gameserver` ADD `gameserverConfigGameserver` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `gameserver` ADD UNIQUE INDEX `IDX_e1489f4b9c2a32ba0cdb3c7023` (`gameserverConfigGameserver`)");
        await queryRunner.query("ALTER TABLE `game` ADD `matchConfigId` int NULL");
        await queryRunner.query("ALTER TABLE `auth_key` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `steam_user` CHANGE `steamId64` `steamId64` int UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `steam_user` CHANGE `lastUpdate` `lastUpdate` datetime NULL");
        await queryRunner.query("ALTER TABLE `transaction_id` CHANGE `resultJSON` `resultJSON` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `FK_97c8d66b4d906bb743fb0d81b93`");
        await queryRunner.query("ALTER TABLE `game_mode` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `FK_e4a9c8d911c2aaeba97e368202b`");
        await queryRunner.query("ALTER TABLE `server_map` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `game` CHANGE `endedAt` `endedAt` datetime NULL");
        await queryRunner.query("ALTER TABLE `game` CHANGE `mapId` `mapId` int UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `game` CHANGE `gameModeId` `gameModeId` int UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` DROP FOREIGN KEY `FK_fe4b0797ce581679cd621c937ef`");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` DROP FOREIGN KEY `FK_6960708d69a3780ee7d90cf8d8b`");
        await queryRunner.query("ALTER TABLE `round` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `round` CHANGE `endedAt` `endedAt` datetime NULL");
        await queryRunner.query("ALTER TABLE `round` CHANGE `scoreSpecialForces` `scoreSpecialForces` smallint UNSIGNED NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `round` CHANGE `scoreTerrorists` `scoreTerrorists` smallint UNSIGNED NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `steamId64` `steamId64` int UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `kills` `kills` smallint UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `deaths` `deaths` smallint UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `suicides` `suicides` smallint UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `totalDamage` `totalDamage` float UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `score` `score` smallint UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `roundId` `roundId` int UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` DROP FOREIGN KEY `FK_818dacb9a37b30976cae4157918`");
        await queryRunner.query("ALTER TABLE `weapon` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `steamId64` `steamId64` int UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `totalDamage` `totalDamage` float UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `shotsHead` `shotsHead` smallint UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `shotsChest` `shotsChest` smallint UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `shotsLegs` `shotsLegs` smallint UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `shotsArms` `shotsArms` smallint UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `shotsFired` `shotsFired` int UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `roundId` `roundId` int UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `weaponId` `weaponId` int UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `ban` DROP FOREIGN KEY `FK_ef6b973ab0ec13728e454d46dc3`");
        await queryRunner.query("ALTER TABLE `ban` CHANGE `steamId64` `steamId64` int UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `ban` CHANGE `bannedById64` `bannedById64` int UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `ban` CHANGE `gameserverId` `gameserverId` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `registered_player` CHANGE `id` `id` int UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `registered_player` CHANGE `steamId64` `steamId64` int UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_e1489f4b9c2a32ba0cdb3c7023` ON `gameserver` (`gameserverConfigGameserver`)");
        await queryRunner.query("ALTER TABLE `match_config` ADD CONSTRAINT `FK_dd7663370fbf217ac794906fc4e` FOREIGN KEY (`gameModeId`) REFERENCES `game_mode`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `gameserver_config` ADD CONSTRAINT `FK_e81629bd2734cc6621e92a88971` FOREIGN KEY (`gameserverId`) REFERENCES `gameserver`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `gameserver_config` ADD CONSTRAINT `FK_8ec518313d27aa5389db772a018` FOREIGN KEY (`currentMatchConfigId`) REFERENCES `match_config`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `gameserver` ADD CONSTRAINT `FK_e1489f4b9c2a32ba0cdb3c70238` FOREIGN KEY (`gameserverConfigGameserver`) REFERENCES `gameserver_config`(`gameserverId`) ON DELETE SET NULL ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `FK_466fe0a5a0188102b3fd889052f` FOREIGN KEY (`matchConfigId`) REFERENCES `match_config`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `FK_e4a9c8d911c2aaeba97e368202b` FOREIGN KEY (`mapId`) REFERENCES `server_map`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `FK_97c8d66b4d906bb743fb0d81b93` FOREIGN KEY (`gameModeId`) REFERENCES `game_mode`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `player_round_stats` ADD CONSTRAINT `FK_fe4b0797ce581679cd621c937ef` FOREIGN KEY (`roundId`) REFERENCES `round`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` ADD CONSTRAINT `FK_6960708d69a3780ee7d90cf8d8b` FOREIGN KEY (`roundId`) REFERENCES `round`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` ADD CONSTRAINT `FK_818dacb9a37b30976cae4157918` FOREIGN KEY (`weaponId`) REFERENCES `weapon`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `ban` ADD CONSTRAINT `FK_ef6b973ab0ec13728e454d46dc3` FOREIGN KEY (`gameserverId`) REFERENCES `gameserver`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `ban` DROP FOREIGN KEY `FK_ef6b973ab0ec13728e454d46dc3`");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` DROP FOREIGN KEY `FK_818dacb9a37b30976cae4157918`");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` DROP FOREIGN KEY `FK_6960708d69a3780ee7d90cf8d8b`");
        await queryRunner.query("ALTER TABLE `player_round_stats` DROP FOREIGN KEY `FK_fe4b0797ce581679cd621c937ef`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `FK_97c8d66b4d906bb743fb0d81b93`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `FK_e4a9c8d911c2aaeba97e368202b`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `FK_466fe0a5a0188102b3fd889052f`");
        await queryRunner.query("ALTER TABLE `gameserver` DROP FOREIGN KEY `FK_e1489f4b9c2a32ba0cdb3c70238`");
        await queryRunner.query("ALTER TABLE `gameserver_config` DROP FOREIGN KEY `FK_8ec518313d27aa5389db772a018`");
        await queryRunner.query("ALTER TABLE `gameserver_config` DROP FOREIGN KEY `FK_e81629bd2734cc6621e92a88971`");
        await queryRunner.query("ALTER TABLE `match_config` DROP FOREIGN KEY `FK_dd7663370fbf217ac794906fc4e`");
        await queryRunner.query("DROP INDEX `REL_e1489f4b9c2a32ba0cdb3c7023` ON `gameserver`");
        await queryRunner.query("ALTER TABLE `registered_player` CHANGE `steamId64` `steamId64` int(10) UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `registered_player` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `ban` CHANGE `gameserverId` `gameserverId` varchar(255) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `ban` CHANGE `bannedById64` `bannedById64` int(10) UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `ban` CHANGE `steamId64` `steamId64` int(10) UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `ban` ADD CONSTRAINT `FK_ef6b973ab0ec13728e454d46dc3` FOREIGN KEY (`gameserverId`) REFERENCES `gameserver`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `weaponId` `weaponId` int(10) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `roundId` `roundId` int(10) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `shotsFired` `shotsFired` int(10) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `shotsArms` `shotsArms` smallint(5) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `shotsLegs` `shotsLegs` smallint(5) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `shotsChest` `shotsChest` smallint(5) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `shotsHead` `shotsHead` smallint(5) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `totalDamage` `totalDamage` float(12) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` CHANGE `steamId64` `steamId64` int(10) UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `weapon` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` ADD CONSTRAINT `FK_818dacb9a37b30976cae4157918` FOREIGN KEY (`weaponId`) REFERENCES `weapon`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `roundId` `roundId` int(10) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `score` `score` smallint(5) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `totalDamage` `totalDamage` float(12) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `suicides` `suicides` smallint(5) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `deaths` `deaths` smallint(5) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `kills` `kills` smallint(5) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `player_round_stats` CHANGE `steamId64` `steamId64` int(10) UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `round` CHANGE `scoreTerrorists` `scoreTerrorists` smallint(5) UNSIGNED NOT NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `round` CHANGE `scoreSpecialForces` `scoreSpecialForces` smallint(5) UNSIGNED NOT NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `round` CHANGE `endedAt` `endedAt` datetime NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `round` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `player_round_weapon_stats` ADD CONSTRAINT `FK_6960708d69a3780ee7d90cf8d8b` FOREIGN KEY (`roundId`) REFERENCES `round`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `player_round_stats` ADD CONSTRAINT `FK_fe4b0797ce581679cd621c937ef` FOREIGN KEY (`roundId`) REFERENCES `round`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` CHANGE `gameModeId` `gameModeId` int(10) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `game` CHANGE `mapId` `mapId` int(10) UNSIGNED NOT NULL");
        await queryRunner.query("ALTER TABLE `game` CHANGE `endedAt` `endedAt` datetime NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `server_map` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `FK_e4a9c8d911c2aaeba97e368202b` FOREIGN KEY (`mapId`) REFERENCES `server_map`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game_mode` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `FK_97c8d66b4d906bb743fb0d81b93` FOREIGN KEY (`gameModeId`) REFERENCES `game_mode`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `transaction_id` CHANGE `resultJSON` `resultJSON` varchar(255) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `steam_user` CHANGE `lastUpdate` `lastUpdate` datetime NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `steam_user` CHANGE `steamId64` `steamId64` int(10) UNSIGNED NOT NULL COMMENT 'Save SteamAccountId to avoid bigint weirdness'");
        await queryRunner.query("ALTER TABLE `auth_key` CHANGE `id` `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `game` DROP COLUMN `matchConfigId`");
        await queryRunner.query("ALTER TABLE `gameserver` DROP INDEX `IDX_e1489f4b9c2a32ba0cdb3c7023`");
        await queryRunner.query("ALTER TABLE `gameserver` DROP COLUMN `gameserverConfigGameserver`");
        await queryRunner.query("DROP INDEX `REL_e81629bd2734cc6621e92a8897` ON `gameserver_config`");
        await queryRunner.query("DROP TABLE `gameserver_config`");
        await queryRunner.query("DROP INDEX `IDX_fbbc00f440d3e086650663cfbc` ON `match_config`");
        await queryRunner.query("DROP INDEX `idx_ranked` ON `match_config`");
        await queryRunner.query("DROP TABLE `match_config`");
    }

}
