import {MigrationInterface, QueryRunner} from "typeorm";

export class init1600690167444 implements MigrationInterface {
    name = 'init1600690167444'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "app_config" ("instanceId" varchar PRIMARY KEY NOT NULL, "publicStats" boolean NOT NULL DEFAULT (0), "banlistPartners" text NOT NULL DEFAULT (''), "publicBanQuery" boolean NOT NULL DEFAULT (0), "masterserverKey" varchar NOT NULL DEFAULT (''), "steamWebApiKey" varchar NOT NULL DEFAULT (''), "ownAddress" varchar NOT NULL DEFAULT (''), "password" varchar NOT NULL, "passwordInitialised" boolean NOT NULL DEFAULT (0), "secret" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "auth_key" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "authKey" varchar NOT NULL, "description" varchar NOT NULL DEFAULT (''), "lastUse" datetime NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b602ae26284d163d16303d997" ON "auth_key" ("authKey") `);
        await queryRunner.query(`CREATE TABLE "steam_user" ("steamId64" integer PRIMARY KEY NOT NULL, "name" varchar NOT NULL DEFAULT (''), "avatarBigUrl" varchar NOT NULL DEFAULT (''), "avatarMediumUrl" varchar NOT NULL DEFAULT (''), "lastUpdate" datetime)`);
        await queryRunner.query(`CREATE INDEX "idx_steamName" ON "steam_user" ("name") `);
        await queryRunner.query(`CREATE TABLE "transaction_id" ("transactionId" varchar PRIMARY KEY NOT NULL, "insertedAt" datetime NOT NULL, "resultJSON" varchar)`);
        await queryRunner.query(`CREATE TABLE "game_mode" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "isTeamBased" boolean NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_044d3c0ab088b8b1f604ac080a" ON "game_mode" ("name") `);
        await queryRunner.query(`CREATE TABLE "gameserver" ("id" varchar PRIMARY KEY NOT NULL, "authKey" varchar NOT NULL, "currentName" varchar NOT NULL DEFAULT (''), "description" varchar NOT NULL DEFAULT (''), "lastContact" datetime NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2c82e7f028dd0320e2cbae75c" ON "gameserver" ("authKey") `);
        await queryRunner.query(`CREATE TABLE "server_map" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7f08167bb58d27be39ed2a4912" ON "server_map" ("name") `);
        await queryRunner.query(`CREATE TABLE "game" ("id" varchar PRIMARY KEY NOT NULL, "startedAt" datetime NOT NULL, "endedAt" datetime, "gameserverId" varchar NOT NULL, "mapId" integer NOT NULL, "gameModeId" integer NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_gameStartedAt" ON "game" ("startedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_gameEndedAt" ON "game" ("endedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_gameGameMode" ON "game" ("gameModeId") `);
        await queryRunner.query(`CREATE TABLE "round" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "startedAt" datetime NOT NULL, "endedAt" datetime, "scoreSpecialForces" smallint NOT NULL DEFAULT (0), "scoreTerrorists" smallint NOT NULL DEFAULT (0), "gameId" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_roundGame" ON "round" ("gameId") `);
        await queryRunner.query(`CREATE INDEX "idx_roundStartedAt" ON "round" ("startedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_roundEndedAt" ON "round" ("endedAt") `);
        await queryRunner.query(`CREATE TABLE "player_round_stats" ("steamId64" integer NOT NULL, "kills" smallint NOT NULL, "deaths" smallint NOT NULL, "suicides" smallint NOT NULL, "totalDamage" float NOT NULL, "score" smallint NOT NULL, "team" smallint NOT NULL, "roundId" integer NOT NULL, PRIMARY KEY ("steamId64", "roundId"))`);
        await queryRunner.query(`CREATE INDEX "idx_steamId" ON "player_round_stats" ("steamId64") `);
        await queryRunner.query(`CREATE TABLE "weapon" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "weaponType" varchar NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c0a6e6eabffa74c4a025ce2eec" ON "weapon" ("name") `);
        await queryRunner.query(`CREATE TABLE "player_round_weapon_stats" ("steamId64" integer NOT NULL, "totalDamage" float NOT NULL, "shotsHead" smallint NOT NULL, "shotsChest" smallint NOT NULL, "shotsLegs" smallint NOT NULL, "shotsArms" smallint NOT NULL, "shotsFired" integer NOT NULL, "roundId" integer NOT NULL, "weaponId" integer NOT NULL, PRIMARY KEY ("steamId64", "roundId", "weaponId"))`);
        await queryRunner.query(`CREATE TABLE "ban" ("id" varchar PRIMARY KEY NOT NULL, "steamId64" integer NOT NULL, "bannedById64" integer NOT NULL, "createdAt" datetime NOT NULL, "expiredAt" datetime NOT NULL, "reason" varchar NOT NULL DEFAULT (''), "id1" varchar NOT NULL DEFAULT (''), "id2" varchar NOT NULL DEFAULT (''), "gameserverId" varchar)`);
        await queryRunner.query(`CREATE INDEX "idx_steamId64" ON "ban" ("steamId64") `);
        await queryRunner.query(`CREATE INDEX "idx_bannedById64" ON "ban" ("bannedById64") `);
        await queryRunner.query(`CREATE INDEX "idx_createdAt" ON "ban" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_expiredAt" ON "ban" ("expiredAt") `);
        await queryRunner.query(`CREATE INDEX "idx_id1" ON "ban" ("id1") `);
        await queryRunner.query(`CREATE INDEX "idx_id2" ON "ban" ("id2") `);
        await queryRunner.query(`CREATE TABLE "registered_player" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "steamId64" integer NOT NULL, "visibleRole" varchar NOT NULL DEFAULT (''), "rootAdmin" boolean NOT NULL DEFAULT (0), "kick" boolean NOT NULL DEFAULT (0), "ban" boolean NOT NULL DEFAULT (0), "tempKickBan" boolean NOT NULL DEFAULT (0), "mute" boolean NOT NULL DEFAULT (0), "makeTeams" boolean NOT NULL DEFAULT (0), "reservedSlots" boolean NOT NULL DEFAULT (0), "broadcastMessage" boolean NOT NULL DEFAULT (0), "gameControl" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e8f1a1e6f7c3deff637482efa8" ON "registered_player" ("steamId64") `);
        await queryRunner.query(`DROP INDEX "idx_gameStartedAt"`);
        await queryRunner.query(`DROP INDEX "idx_gameEndedAt"`);
        await queryRunner.query(`DROP INDEX "idx_gameGameMode"`);
        await queryRunner.query(`CREATE TABLE "temporary_game" ("id" varchar PRIMARY KEY NOT NULL, "startedAt" datetime NOT NULL, "endedAt" datetime, "gameserverId" varchar NOT NULL, "mapId" integer NOT NULL, "gameModeId" integer NOT NULL, CONSTRAINT "FK_2373cf05d5aec448112acc93b73" FOREIGN KEY ("gameserverId") REFERENCES "gameserver" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_e4a9c8d911c2aaeba97e368202b" FOREIGN KEY ("mapId") REFERENCES "server_map" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_97c8d66b4d906bb743fb0d81b93" FOREIGN KEY ("gameModeId") REFERENCES "game_mode" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_game"("id", "startedAt", "endedAt", "gameserverId", "mapId", "gameModeId") SELECT "id", "startedAt", "endedAt", "gameserverId", "mapId", "gameModeId" FROM "game"`);
        await queryRunner.query(`DROP TABLE "game"`);
        await queryRunner.query(`ALTER TABLE "temporary_game" RENAME TO "game"`);
        await queryRunner.query(`CREATE INDEX "idx_gameStartedAt" ON "game" ("startedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_gameEndedAt" ON "game" ("endedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_gameGameMode" ON "game" ("gameModeId") `);
        await queryRunner.query(`DROP INDEX "idx_roundGame"`);
        await queryRunner.query(`DROP INDEX "idx_roundStartedAt"`);
        await queryRunner.query(`DROP INDEX "idx_roundEndedAt"`);
        await queryRunner.query(`CREATE TABLE "temporary_round" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "startedAt" datetime NOT NULL, "endedAt" datetime, "scoreSpecialForces" smallint NOT NULL DEFAULT (0), "scoreTerrorists" smallint NOT NULL DEFAULT (0), "gameId" varchar NOT NULL, CONSTRAINT "FK_e4d9372889dee36f0a4be7f25e6" FOREIGN KEY ("gameId") REFERENCES "game" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_round"("id", "startedAt", "endedAt", "scoreSpecialForces", "scoreTerrorists", "gameId") SELECT "id", "startedAt", "endedAt", "scoreSpecialForces", "scoreTerrorists", "gameId" FROM "round"`);
        await queryRunner.query(`DROP TABLE "round"`);
        await queryRunner.query(`ALTER TABLE "temporary_round" RENAME TO "round"`);
        await queryRunner.query(`CREATE INDEX "idx_roundGame" ON "round" ("gameId") `);
        await queryRunner.query(`CREATE INDEX "idx_roundStartedAt" ON "round" ("startedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_roundEndedAt" ON "round" ("endedAt") `);
        await queryRunner.query(`DROP INDEX "idx_steamId"`);
        await queryRunner.query(`CREATE TABLE "temporary_player_round_stats" ("steamId64" integer NOT NULL, "kills" smallint NOT NULL, "deaths" smallint NOT NULL, "suicides" smallint NOT NULL, "totalDamage" float NOT NULL, "score" smallint NOT NULL, "team" smallint NOT NULL, "roundId" integer NOT NULL, CONSTRAINT "FK_fe4b0797ce581679cd621c937ef" FOREIGN KEY ("roundId") REFERENCES "round" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("steamId64", "roundId"))`);
        await queryRunner.query(`INSERT INTO "temporary_player_round_stats"("steamId64", "kills", "deaths", "suicides", "totalDamage", "score", "team", "roundId") SELECT "steamId64", "kills", "deaths", "suicides", "totalDamage", "score", "team", "roundId" FROM "player_round_stats"`);
        await queryRunner.query(`DROP TABLE "player_round_stats"`);
        await queryRunner.query(`ALTER TABLE "temporary_player_round_stats" RENAME TO "player_round_stats"`);
        await queryRunner.query(`CREATE INDEX "idx_steamId" ON "player_round_stats" ("steamId64") `);
        await queryRunner.query(`CREATE TABLE "temporary_player_round_weapon_stats" ("steamId64" integer NOT NULL, "totalDamage" float NOT NULL, "shotsHead" smallint NOT NULL, "shotsChest" smallint NOT NULL, "shotsLegs" smallint NOT NULL, "shotsArms" smallint NOT NULL, "shotsFired" integer NOT NULL, "roundId" integer NOT NULL, "weaponId" integer NOT NULL, CONSTRAINT "FK_6960708d69a3780ee7d90cf8d8b" FOREIGN KEY ("roundId") REFERENCES "round" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_818dacb9a37b30976cae4157918" FOREIGN KEY ("weaponId") REFERENCES "weapon" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("steamId64", "roundId", "weaponId"))`);
        await queryRunner.query(`INSERT INTO "temporary_player_round_weapon_stats"("steamId64", "totalDamage", "shotsHead", "shotsChest", "shotsLegs", "shotsArms", "shotsFired", "roundId", "weaponId") SELECT "steamId64", "totalDamage", "shotsHead", "shotsChest", "shotsLegs", "shotsArms", "shotsFired", "roundId", "weaponId" FROM "player_round_weapon_stats"`);
        await queryRunner.query(`DROP TABLE "player_round_weapon_stats"`);
        await queryRunner.query(`ALTER TABLE "temporary_player_round_weapon_stats" RENAME TO "player_round_weapon_stats"`);
        await queryRunner.query(`DROP INDEX "idx_steamId64"`);
        await queryRunner.query(`DROP INDEX "idx_bannedById64"`);
        await queryRunner.query(`DROP INDEX "idx_createdAt"`);
        await queryRunner.query(`DROP INDEX "idx_expiredAt"`);
        await queryRunner.query(`DROP INDEX "idx_id1"`);
        await queryRunner.query(`DROP INDEX "idx_id2"`);
        await queryRunner.query(`CREATE TABLE "temporary_ban" ("id" varchar PRIMARY KEY NOT NULL, "steamId64" integer NOT NULL, "bannedById64" integer NOT NULL, "createdAt" datetime NOT NULL, "expiredAt" datetime NOT NULL, "reason" varchar NOT NULL DEFAULT (''), "id1" varchar NOT NULL DEFAULT (''), "id2" varchar NOT NULL DEFAULT (''), "gameserverId" varchar, CONSTRAINT "FK_ef6b973ab0ec13728e454d46dc3" FOREIGN KEY ("gameserverId") REFERENCES "gameserver" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ban"("id", "steamId64", "bannedById64", "createdAt", "expiredAt", "reason", "id1", "id2", "gameserverId") SELECT "id", "steamId64", "bannedById64", "createdAt", "expiredAt", "reason", "id1", "id2", "gameserverId" FROM "ban"`);
        await queryRunner.query(`DROP TABLE "ban"`);
        await queryRunner.query(`ALTER TABLE "temporary_ban" RENAME TO "ban"`);
        await queryRunner.query(`CREATE INDEX "idx_steamId64" ON "ban" ("steamId64") `);
        await queryRunner.query(`CREATE INDEX "idx_bannedById64" ON "ban" ("bannedById64") `);
        await queryRunner.query(`CREATE INDEX "idx_createdAt" ON "ban" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_expiredAt" ON "ban" ("expiredAt") `);
        await queryRunner.query(`CREATE INDEX "idx_id1" ON "ban" ("id1") `);
        await queryRunner.query(`CREATE INDEX "idx_id2" ON "ban" ("id2") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "idx_id2"`);
        await queryRunner.query(`DROP INDEX "idx_id1"`);
        await queryRunner.query(`DROP INDEX "idx_expiredAt"`);
        await queryRunner.query(`DROP INDEX "idx_createdAt"`);
        await queryRunner.query(`DROP INDEX "idx_bannedById64"`);
        await queryRunner.query(`DROP INDEX "idx_steamId64"`);
        await queryRunner.query(`ALTER TABLE "ban" RENAME TO "temporary_ban"`);
        await queryRunner.query(`CREATE TABLE "ban" ("id" varchar PRIMARY KEY NOT NULL, "steamId64" integer NOT NULL, "bannedById64" integer NOT NULL, "createdAt" datetime NOT NULL, "expiredAt" datetime NOT NULL, "reason" varchar NOT NULL DEFAULT (''), "id1" varchar NOT NULL DEFAULT (''), "id2" varchar NOT NULL DEFAULT (''), "gameserverId" varchar)`);
        await queryRunner.query(`INSERT INTO "ban"("id", "steamId64", "bannedById64", "createdAt", "expiredAt", "reason", "id1", "id2", "gameserverId") SELECT "id", "steamId64", "bannedById64", "createdAt", "expiredAt", "reason", "id1", "id2", "gameserverId" FROM "temporary_ban"`);
        await queryRunner.query(`DROP TABLE "temporary_ban"`);
        await queryRunner.query(`CREATE INDEX "idx_id2" ON "ban" ("id2") `);
        await queryRunner.query(`CREATE INDEX "idx_id1" ON "ban" ("id1") `);
        await queryRunner.query(`CREATE INDEX "idx_expiredAt" ON "ban" ("expiredAt") `);
        await queryRunner.query(`CREATE INDEX "idx_createdAt" ON "ban" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_bannedById64" ON "ban" ("bannedById64") `);
        await queryRunner.query(`CREATE INDEX "idx_steamId64" ON "ban" ("steamId64") `);
        await queryRunner.query(`ALTER TABLE "player_round_weapon_stats" RENAME TO "temporary_player_round_weapon_stats"`);
        await queryRunner.query(`CREATE TABLE "player_round_weapon_stats" ("steamId64" integer NOT NULL, "totalDamage" float NOT NULL, "shotsHead" smallint NOT NULL, "shotsChest" smallint NOT NULL, "shotsLegs" smallint NOT NULL, "shotsArms" smallint NOT NULL, "shotsFired" integer NOT NULL, "roundId" integer NOT NULL, "weaponId" integer NOT NULL, PRIMARY KEY ("steamId64", "roundId", "weaponId"))`);
        await queryRunner.query(`INSERT INTO "player_round_weapon_stats"("steamId64", "totalDamage", "shotsHead", "shotsChest", "shotsLegs", "shotsArms", "shotsFired", "roundId", "weaponId") SELECT "steamId64", "totalDamage", "shotsHead", "shotsChest", "shotsLegs", "shotsArms", "shotsFired", "roundId", "weaponId" FROM "temporary_player_round_weapon_stats"`);
        await queryRunner.query(`DROP TABLE "temporary_player_round_weapon_stats"`);
        await queryRunner.query(`DROP INDEX "idx_steamId"`);
        await queryRunner.query(`ALTER TABLE "player_round_stats" RENAME TO "temporary_player_round_stats"`);
        await queryRunner.query(`CREATE TABLE "player_round_stats" ("steamId64" integer NOT NULL, "kills" smallint NOT NULL, "deaths" smallint NOT NULL, "suicides" smallint NOT NULL, "totalDamage" float NOT NULL, "score" smallint NOT NULL, "team" smallint NOT NULL, "roundId" integer NOT NULL, PRIMARY KEY ("steamId64", "roundId"))`);
        await queryRunner.query(`INSERT INTO "player_round_stats"("steamId64", "kills", "deaths", "suicides", "totalDamage", "score", "team", "roundId") SELECT "steamId64", "kills", "deaths", "suicides", "totalDamage", "score", "team", "roundId" FROM "temporary_player_round_stats"`);
        await queryRunner.query(`DROP TABLE "temporary_player_round_stats"`);
        await queryRunner.query(`CREATE INDEX "idx_steamId" ON "player_round_stats" ("steamId64") `);
        await queryRunner.query(`DROP INDEX "idx_roundEndedAt"`);
        await queryRunner.query(`DROP INDEX "idx_roundStartedAt"`);
        await queryRunner.query(`DROP INDEX "idx_roundGame"`);
        await queryRunner.query(`ALTER TABLE "round" RENAME TO "temporary_round"`);
        await queryRunner.query(`CREATE TABLE "round" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "startedAt" datetime NOT NULL, "endedAt" datetime, "scoreSpecialForces" smallint NOT NULL DEFAULT (0), "scoreTerrorists" smallint NOT NULL DEFAULT (0), "gameId" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "round"("id", "startedAt", "endedAt", "scoreSpecialForces", "scoreTerrorists", "gameId") SELECT "id", "startedAt", "endedAt", "scoreSpecialForces", "scoreTerrorists", "gameId" FROM "temporary_round"`);
        await queryRunner.query(`DROP TABLE "temporary_round"`);
        await queryRunner.query(`CREATE INDEX "idx_roundEndedAt" ON "round" ("endedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_roundStartedAt" ON "round" ("startedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_roundGame" ON "round" ("gameId") `);
        await queryRunner.query(`DROP INDEX "idx_gameGameMode"`);
        await queryRunner.query(`DROP INDEX "idx_gameEndedAt"`);
        await queryRunner.query(`DROP INDEX "idx_gameStartedAt"`);
        await queryRunner.query(`ALTER TABLE "game" RENAME TO "temporary_game"`);
        await queryRunner.query(`CREATE TABLE "game" ("id" varchar PRIMARY KEY NOT NULL, "startedAt" datetime NOT NULL, "endedAt" datetime, "gameserverId" varchar NOT NULL, "mapId" integer NOT NULL, "gameModeId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "game"("id", "startedAt", "endedAt", "gameserverId", "mapId", "gameModeId") SELECT "id", "startedAt", "endedAt", "gameserverId", "mapId", "gameModeId" FROM "temporary_game"`);
        await queryRunner.query(`DROP TABLE "temporary_game"`);
        await queryRunner.query(`CREATE INDEX "idx_gameGameMode" ON "game" ("gameModeId") `);
        await queryRunner.query(`CREATE INDEX "idx_gameEndedAt" ON "game" ("endedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_gameStartedAt" ON "game" ("startedAt") `);
        await queryRunner.query(`DROP INDEX "IDX_e8f1a1e6f7c3deff637482efa8"`);
        await queryRunner.query(`DROP TABLE "registered_player"`);
        await queryRunner.query(`DROP INDEX "idx_id2"`);
        await queryRunner.query(`DROP INDEX "idx_id1"`);
        await queryRunner.query(`DROP INDEX "idx_expiredAt"`);
        await queryRunner.query(`DROP INDEX "idx_createdAt"`);
        await queryRunner.query(`DROP INDEX "idx_bannedById64"`);
        await queryRunner.query(`DROP INDEX "idx_steamId64"`);
        await queryRunner.query(`DROP TABLE "ban"`);
        await queryRunner.query(`DROP TABLE "player_round_weapon_stats"`);
        await queryRunner.query(`DROP INDEX "IDX_c0a6e6eabffa74c4a025ce2eec"`);
        await queryRunner.query(`DROP TABLE "weapon"`);
        await queryRunner.query(`DROP INDEX "idx_steamId"`);
        await queryRunner.query(`DROP TABLE "player_round_stats"`);
        await queryRunner.query(`DROP INDEX "idx_roundEndedAt"`);
        await queryRunner.query(`DROP INDEX "idx_roundStartedAt"`);
        await queryRunner.query(`DROP INDEX "idx_roundGame"`);
        await queryRunner.query(`DROP TABLE "round"`);
        await queryRunner.query(`DROP INDEX "idx_gameGameMode"`);
        await queryRunner.query(`DROP INDEX "idx_gameEndedAt"`);
        await queryRunner.query(`DROP INDEX "idx_gameStartedAt"`);
        await queryRunner.query(`DROP TABLE "game"`);
        await queryRunner.query(`DROP INDEX "IDX_7f08167bb58d27be39ed2a4912"`);
        await queryRunner.query(`DROP TABLE "server_map"`);
        await queryRunner.query(`DROP INDEX "IDX_b2c82e7f028dd0320e2cbae75c"`);
        await queryRunner.query(`DROP TABLE "gameserver"`);
        await queryRunner.query(`DROP INDEX "IDX_044d3c0ab088b8b1f604ac080a"`);
        await queryRunner.query(`DROP TABLE "game_mode"`);
        await queryRunner.query(`DROP TABLE "transaction_id"`);
        await queryRunner.query(`DROP INDEX "idx_steamName"`);
        await queryRunner.query(`DROP TABLE "steam_user"`);
        await queryRunner.query(`DROP INDEX "IDX_5b602ae26284d163d16303d997"`);
        await queryRunner.query(`DROP TABLE "auth_key"`);
        await queryRunner.query(`DROP TABLE "app_config"`);
    }

}
