import {MigrationInterface, QueryRunner} from "typeorm";

export class playerStatsCache1607713727799 implements MigrationInterface {
    name = 'playerStatsCache1607713727799'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "FK_8ec518313d27aa5389db772a018" FOREIGN KEY ("currentMatchConfigId") REFERENCES "match_config" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e81629bd2734cc6621e92a88971" FOREIGN KEY ("gameserverId") REFERENCES "gameserver" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "gameserver_config"`);
        await queryRunner.query(`DROP TABLE "gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver_config" RENAME TO "gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "temporary_app_config" ("instanceId" varchar PRIMARY KEY NOT NULL, "publicStats" boolean NOT NULL DEFAULT (0), "banlistPartners" text NOT NULL DEFAULT (''), "publicBanQuery" boolean NOT NULL DEFAULT (0), "masterserverKey" varchar NOT NULL DEFAULT (''), "steamWebApiKey" varchar NOT NULL DEFAULT (''), "ownAddress" varchar NOT NULL DEFAULT (''), "password" varchar NOT NULL, "passwordInitialised" boolean NOT NULL DEFAULT (0), "secret" varchar NOT NULL, "playerStatsCacheAge" smallint NOT NULL DEFAULT (5), "minScoreStats" integer NOT NULL DEFAULT (100))`);
        await queryRunner.query(`INSERT INTO "temporary_app_config"("instanceId", "publicStats", "banlistPartners", "publicBanQuery", "masterserverKey", "steamWebApiKey", "ownAddress", "password", "passwordInitialised", "secret") SELECT "instanceId", "publicStats", "banlistPartners", "publicBanQuery", "masterserverKey", "steamWebApiKey", "ownAddress", "password", "passwordInitialised", "secret" FROM "app_config"`);
        await queryRunner.query(`DROP TABLE "app_config"`);
        await queryRunner.query(`ALTER TABLE "temporary_app_config" RENAME TO "app_config"`);
        await queryRunner.query(`CREATE TABLE "temporary_gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "gameserver_config"`);
        await queryRunner.query(`DROP TABLE "gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver_config" RENAME TO "gameserver_config"`);
        await queryRunner.query(`DROP INDEX "IDX_b2c82e7f028dd0320e2cbae75c"`);
        await queryRunner.query(`CREATE TABLE "temporary_gameserver" ("id" varchar PRIMARY KEY NOT NULL, "authKey" varchar NOT NULL, "currentName" varchar NOT NULL DEFAULT (''), "description" varchar NOT NULL DEFAULT (''), "lastContact" datetime NOT NULL, "gameserverConfigGameserver" varchar, CONSTRAINT "UQ_e1489f4b9c2a32ba0cdb3c70238" UNIQUE ("gameserverConfigGameserver"))`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver"("id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver") SELECT "id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver" FROM "gameserver"`);
        await queryRunner.query(`DROP TABLE "gameserver"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver" RENAME TO "gameserver"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2c82e7f028dd0320e2cbae75c" ON "gameserver" ("authKey") `);
        await queryRunner.query(`CREATE TABLE "temporary_gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "UQ_c99a2565cf861388839c51d99b9" UNIQUE ("gameserverId"))`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "gameserver_config"`);
        await queryRunner.query(`DROP TABLE "gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver_config" RENAME TO "gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "temporary_gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "UQ_c99a2565cf861388839c51d99b9" UNIQUE ("gameserverId"), CONSTRAINT "FK_e81629bd2734cc6621e92a88971" FOREIGN KEY ("gameserverId") REFERENCES "gameserver" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_8ec518313d27aa5389db772a018" FOREIGN KEY ("currentMatchConfigId") REFERENCES "match_config" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "gameserver_config"`);
        await queryRunner.query(`DROP TABLE "gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver_config" RENAME TO "gameserver_config"`);
        await queryRunner.query(`DROP INDEX "IDX_b2c82e7f028dd0320e2cbae75c"`);
        await queryRunner.query(`CREATE TABLE "temporary_gameserver" ("id" varchar PRIMARY KEY NOT NULL, "authKey" varchar NOT NULL, "currentName" varchar NOT NULL DEFAULT (''), "description" varchar NOT NULL DEFAULT (''), "lastContact" datetime NOT NULL, "gameserverConfigGameserver" varchar, CONSTRAINT "UQ_e1489f4b9c2a32ba0cdb3c70238" UNIQUE ("gameserverConfigGameserver"), CONSTRAINT "FK_e1489f4b9c2a32ba0cdb3c70238" FOREIGN KEY ("gameserverConfigGameserver") REFERENCES "gameserver_config" ("gameserverId") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver"("id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver") SELECT "id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver" FROM "gameserver"`);
        await queryRunner.query(`DROP TABLE "gameserver"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver" RENAME TO "gameserver"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2c82e7f028dd0320e2cbae75c" ON "gameserver" ("authKey") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_b2c82e7f028dd0320e2cbae75c"`);
        await queryRunner.query(`ALTER TABLE "gameserver" RENAME TO "temporary_gameserver"`);
        await queryRunner.query(`CREATE TABLE "gameserver" ("id" varchar PRIMARY KEY NOT NULL, "authKey" varchar NOT NULL, "currentName" varchar NOT NULL DEFAULT (''), "description" varchar NOT NULL DEFAULT (''), "lastContact" datetime NOT NULL, "gameserverConfigGameserver" varchar, CONSTRAINT "UQ_e1489f4b9c2a32ba0cdb3c70238" UNIQUE ("gameserverConfigGameserver"))`);
        await queryRunner.query(`INSERT INTO "gameserver"("id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver") SELECT "id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver" FROM "temporary_gameserver"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2c82e7f028dd0320e2cbae75c" ON "gameserver" ("authKey") `);
        await queryRunner.query(`ALTER TABLE "gameserver_config" RENAME TO "temporary_gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "UQ_c99a2565cf861388839c51d99b9" UNIQUE ("gameserverId"))`);
        await queryRunner.query(`INSERT INTO "gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "temporary_gameserver_config"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "gameserver_config" RENAME TO "temporary_gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "temporary_gameserver_config"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver_config"`);
        await queryRunner.query(`DROP INDEX "IDX_b2c82e7f028dd0320e2cbae75c"`);
        await queryRunner.query(`ALTER TABLE "gameserver" RENAME TO "temporary_gameserver"`);
        await queryRunner.query(`CREATE TABLE "gameserver" ("id" varchar PRIMARY KEY NOT NULL, "authKey" varchar NOT NULL, "currentName" varchar NOT NULL DEFAULT (''), "description" varchar NOT NULL DEFAULT (''), "lastContact" datetime NOT NULL, "gameserverConfigGameserver" varchar, CONSTRAINT "UQ_e1489f4b9c2a32ba0cdb3c70238" UNIQUE ("gameserverConfigGameserver"), CONSTRAINT "FK_e1489f4b9c2a32ba0cdb3c70238" FOREIGN KEY ("gameserverConfigGameserver") REFERENCES "gameserver_config" ("gameserverId") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "gameserver"("id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver") SELECT "id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver" FROM "temporary_gameserver"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2c82e7f028dd0320e2cbae75c" ON "gameserver" ("authKey") `);
        await queryRunner.query(`ALTER TABLE "gameserver_config" RENAME TO "temporary_gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "FK_e81629bd2734cc6621e92a88971" FOREIGN KEY ("gameserverId") REFERENCES "gameserver" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "temporary_gameserver_config"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "app_config" RENAME TO "temporary_app_config"`);
        await queryRunner.query(`CREATE TABLE "app_config" ("instanceId" varchar PRIMARY KEY NOT NULL, "publicStats" boolean NOT NULL DEFAULT (0), "banlistPartners" text NOT NULL DEFAULT (''), "publicBanQuery" boolean NOT NULL DEFAULT (0), "masterserverKey" varchar NOT NULL DEFAULT (''), "steamWebApiKey" varchar NOT NULL DEFAULT (''), "ownAddress" varchar NOT NULL DEFAULT (''), "password" varchar NOT NULL, "passwordInitialised" boolean NOT NULL DEFAULT (0), "secret" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "app_config"("instanceId", "publicStats", "banlistPartners", "publicBanQuery", "masterserverKey", "steamWebApiKey", "ownAddress", "password", "passwordInitialised", "secret") SELECT "instanceId", "publicStats", "banlistPartners", "publicBanQuery", "masterserverKey", "steamWebApiKey", "ownAddress", "password", "passwordInitialised", "secret" FROM "temporary_app_config"`);
        await queryRunner.query(`DROP TABLE "temporary_app_config"`);
        await queryRunner.query(`ALTER TABLE "gameserver_config" RENAME TO "temporary_gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "FK_8ec518313d27aa5389db772a018" FOREIGN KEY ("currentMatchConfigId") REFERENCES "match_config" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e81629bd2734cc6621e92a88971" FOREIGN KEY ("gameserverId") REFERENCES "gameserver" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "temporary_gameserver_config"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver_config"`);
    }

}
