import {MigrationInterface, QueryRunner} from "typeorm";

export class defaultAvatarUrls1619126521632 implements MigrationInterface {
    name = 'defaultAvatarUrls1619126521632'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "FK_8ec518313d27aa5389db772a018" FOREIGN KEY ("currentMatchConfigId") REFERENCES "match_config" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e81629bd2734cc6621e92a88971" FOREIGN KEY ("gameserverId") REFERENCES "gameserver" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "gameserver_config"`);
        await queryRunner.query(`DROP TABLE "gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver_config" RENAME TO "gameserver_config"`);
        await queryRunner.query(`DROP INDEX "idx_steamName"`);
        await queryRunner.query(`CREATE TABLE "temporary_steam_user" ("steamId64" integer PRIMARY KEY NOT NULL, "name" varchar NOT NULL DEFAULT (''), "avatarBigUrl" varchar NOT NULL DEFAULT ('https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/c5/c5d56249ee5d28a07db4ac9f7f60af961fab5426_full.jpg'), "avatarMediumUrl" varchar NOT NULL DEFAULT ('https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/c5/c5d56249ee5d28a07db4ac9f7f60af961fab5426_medium.jpg'), "lastUpdate" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_steam_user"("steamId64", "name", "avatarBigUrl", "avatarMediumUrl", "lastUpdate") SELECT "steamId64", "name", "avatarBigUrl", "avatarMediumUrl", "lastUpdate" FROM "steam_user"`);
        await queryRunner.query(`DROP TABLE "steam_user"`);
        await queryRunner.query(`ALTER TABLE "temporary_steam_user" RENAME TO "steam_user"`);
        await queryRunner.query(`CREATE INDEX "idx_steamName" ON "steam_user" ("name") `);
        await queryRunner.query(`CREATE TABLE "temporary_gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "gameserver_config"`);
        await queryRunner.query(`DROP TABLE "gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver_config" RENAME TO "gameserver_config"`);
        await queryRunner.query(`DROP INDEX "IDX_b2c82e7f028dd0320e2cbae75c"`);
        await queryRunner.query(`CREATE TABLE "temporary_gameserver" ("id" varchar PRIMARY KEY NOT NULL, "authKey" varchar NOT NULL, "currentName" varchar NOT NULL DEFAULT (''), "description" varchar NOT NULL DEFAULT (''), "lastContact" datetime NOT NULL, "gameserverConfigGameserver" varchar, CONSTRAINT "UQ_e1489f4b9c2a32ba0cdb3c70238" UNIQUE ("gameserverConfigGameserver"))`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver"("id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver") SELECT "id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver" FROM "gameserver"`);
        await queryRunner.query(`DROP TABLE "gameserver"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver" RENAME TO "gameserver"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2c82e7f028dd0320e2cbae75c" ON "gameserver" ("authKey") `);
        await queryRunner.query(`CREATE TABLE "temporary_gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "UQ_c99a2565cf861388839c51d99b9" UNIQUE ("gameserverId"))`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "gameserver_config"`);
        await queryRunner.query(`DROP TABLE "gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver_config" RENAME TO "gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "temporary_gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "UQ_c99a2565cf861388839c51d99b9" UNIQUE ("gameserverId"), CONSTRAINT "FK_e81629bd2734cc6621e92a88971" FOREIGN KEY ("gameserverId") REFERENCES "gameserver" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_8ec518313d27aa5389db772a018" FOREIGN KEY ("currentMatchConfigId") REFERENCES "match_config" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "gameserver_config"`);
        await queryRunner.query(`DROP TABLE "gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver_config" RENAME TO "gameserver_config"`);
        await queryRunner.query(`DROP INDEX "IDX_b2c82e7f028dd0320e2cbae75c"`);
        await queryRunner.query(`CREATE TABLE "temporary_gameserver" ("id" varchar PRIMARY KEY NOT NULL, "authKey" varchar NOT NULL, "currentName" varchar NOT NULL DEFAULT (''), "description" varchar NOT NULL DEFAULT (''), "lastContact" datetime NOT NULL, "gameserverConfigGameserver" varchar, CONSTRAINT "UQ_e1489f4b9c2a32ba0cdb3c70238" UNIQUE ("gameserverConfigGameserver"), CONSTRAINT "FK_e1489f4b9c2a32ba0cdb3c70238" FOREIGN KEY ("gameserverConfigGameserver") REFERENCES "gameserver_config" ("gameserverId") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_gameserver"("id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver") SELECT "id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver" FROM "gameserver"`);
        await queryRunner.query(`DROP TABLE "gameserver"`);
        await queryRunner.query(`ALTER TABLE "temporary_gameserver" RENAME TO "gameserver"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2c82e7f028dd0320e2cbae75c" ON "gameserver" ("authKey") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_b2c82e7f028dd0320e2cbae75c"`);
        await queryRunner.query(`ALTER TABLE "gameserver" RENAME TO "temporary_gameserver"`);
        await queryRunner.query(`CREATE TABLE "gameserver" ("id" varchar PRIMARY KEY NOT NULL, "authKey" varchar NOT NULL, "currentName" varchar NOT NULL DEFAULT (''), "description" varchar NOT NULL DEFAULT (''), "lastContact" datetime NOT NULL, "gameserverConfigGameserver" varchar, CONSTRAINT "UQ_e1489f4b9c2a32ba0cdb3c70238" UNIQUE ("gameserverConfigGameserver"))`);
        await queryRunner.query(`INSERT INTO "gameserver"("id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver") SELECT "id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver" FROM "temporary_gameserver"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2c82e7f028dd0320e2cbae75c" ON "gameserver" ("authKey") `);
        await queryRunner.query(`ALTER TABLE "gameserver_config" RENAME TO "temporary_gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "UQ_c99a2565cf861388839c51d99b9" UNIQUE ("gameserverId"))`);
        await queryRunner.query(`INSERT INTO "gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "temporary_gameserver_config"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver_config"`);
        await queryRunner.query(`ALTER TABLE "gameserver_config" RENAME TO "temporary_gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "temporary_gameserver_config"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver_config"`);
        await queryRunner.query(`DROP INDEX "IDX_b2c82e7f028dd0320e2cbae75c"`);
        await queryRunner.query(`ALTER TABLE "gameserver" RENAME TO "temporary_gameserver"`);
        await queryRunner.query(`CREATE TABLE "gameserver" ("id" varchar PRIMARY KEY NOT NULL, "authKey" varchar NOT NULL, "currentName" varchar NOT NULL DEFAULT (''), "description" varchar NOT NULL DEFAULT (''), "lastContact" datetime NOT NULL, "gameserverConfigGameserver" varchar, CONSTRAINT "UQ_e1489f4b9c2a32ba0cdb3c70238" UNIQUE ("gameserverConfigGameserver"), CONSTRAINT "FK_e1489f4b9c2a32ba0cdb3c70238" FOREIGN KEY ("gameserverConfigGameserver") REFERENCES "gameserver_config" ("gameserverId") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "gameserver"("id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver") SELECT "id", "authKey", "currentName", "description", "lastContact", "gameserverConfigGameserver" FROM "temporary_gameserver"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2c82e7f028dd0320e2cbae75c" ON "gameserver" ("authKey") `);
        await queryRunner.query(`ALTER TABLE "gameserver_config" RENAME TO "temporary_gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "FK_e81629bd2734cc6621e92a88971" FOREIGN KEY ("gameserverId") REFERENCES "gameserver" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "temporary_gameserver_config"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver_config"`);
        await queryRunner.query(`DROP INDEX "idx_steamName"`);
        await queryRunner.query(`ALTER TABLE "steam_user" RENAME TO "temporary_steam_user"`);
        await queryRunner.query(`CREATE TABLE "steam_user" ("steamId64" integer PRIMARY KEY NOT NULL, "name" varchar NOT NULL DEFAULT (''), "avatarBigUrl" varchar NOT NULL DEFAULT (''), "avatarMediumUrl" varchar NOT NULL DEFAULT (''), "lastUpdate" datetime)`);
        await queryRunner.query(`INSERT INTO "steam_user"("steamId64", "name", "avatarBigUrl", "avatarMediumUrl", "lastUpdate") SELECT "steamId64", "name", "avatarBigUrl", "avatarMediumUrl", "lastUpdate" FROM "temporary_steam_user"`);
        await queryRunner.query(`DROP TABLE "temporary_steam_user"`);
        await queryRunner.query(`CREATE INDEX "idx_steamName" ON "steam_user" ("name") `);
        await queryRunner.query(`ALTER TABLE "gameserver_config" RENAME TO "temporary_gameserver_config"`);
        await queryRunner.query(`CREATE TABLE "gameserver_config" ("currentName" varchar NOT NULL, "voteLength" smallint NOT NULL, "gamePassword" varchar NOT NULL, "reservedSlots" smallint NOT NULL, "balanceClans" boolean NOT NULL, "allowSkipMapVote" boolean NOT NULL, "tempKickBanTime" smallint NOT NULL, "autoRecordReplay" boolean NOT NULL, "playerGameControl" boolean NOT NULL, "enableMapVote" boolean NOT NULL, "serverAdmins" varchar NOT NULL DEFAULT (''), "serverDescription" varchar NOT NULL DEFAULT (''), "website" varchar NOT NULL DEFAULT (''), "contact" varchar NOT NULL DEFAULT (''), "mapNoReplay" smallint NOT NULL, "enableVoicechat" boolean NOT NULL, "gameserverId" varchar PRIMARY KEY NOT NULL, "currentMatchConfigId" integer NOT NULL, CONSTRAINT "FK_8ec518313d27aa5389db772a018" FOREIGN KEY ("currentMatchConfigId") REFERENCES "match_config" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e81629bd2734cc6621e92a88971" FOREIGN KEY ("gameserverId") REFERENCES "gameserver" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "gameserver_config"("currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId") SELECT "currentName", "voteLength", "gamePassword", "reservedSlots", "balanceClans", "allowSkipMapVote", "tempKickBanTime", "autoRecordReplay", "playerGameControl", "enableMapVote", "serverAdmins", "serverDescription", "website", "contact", "mapNoReplay", "enableVoicechat", "gameserverId", "currentMatchConfigId" FROM "temporary_gameserver_config"`);
        await queryRunner.query(`DROP TABLE "temporary_gameserver_config"`);
    }

}
